#ifndef SERVER_HPP
# define SERVER_HPP

# include "main.hpp"
# include "Trie.hpp"
# include "Server.hpp"
# include "Client.hpp"
# include "Channel.hpp"
# include <iostream>
# include <sstream>
# include <queue>
# define SOCK_DOMAIN AF_LOCAL

# define  MAX_SOCKET_FD 2048U

class Server {
	typedef bool (Server::*cmdFn)(Client &c, std::istringstream &rest);
	typedef bool (Server::*replyMsg)(Client &c);
	private:
		uint16_t				_port;
		int						_sockServerFD;
		std::string				_password;
		std::string				_ip;
		Trie<Server::cmdFn>		_commands;
		Trie<int>				_clientTrie;
		std::vector<Client *>	_clients;
		Trie<Channel *>			_channelTrie;
		std::list<Channel>		_channel;
		Trie<Server::replyMsg>	_replyMsg;
		// bool					_init();
		// bool					_clientAdd();

		bool					_validateAccess(Client *c, std::string &command);
		bool    				_validateCommand(cmdFn &func, std::string &command);
		Server() {};
		Server(const Server &src) {(void)src;};
	public:
		Server(uint16_t port, std::string password);
		~Server();
		// std::pair<size_t, std::string>	getVals();
		int 							newConnection();
		void							delClient(int fd);
		bool							run();
		bool							doCommand(size_t fd);
		Client							&getClient(size_t fd);
		// void							setClient(size_t fd);
		std::string						getIp(void) const;
		void							setIp(std::string ip);
		bool							sendToClient(Client &source, std::string message);
		bool							sendRPLToClient(Client &source, std::string message, uint16_t code);
		void							deconnectClient(int fd, std::string error, std::string message);
		std::queue<int>					poolOut;
		std::vector<int>				poolQuit;
		// std::vector<int>				poolInt;
		// c'est horrible
		bool handle_admin(Client &c, std::istringstream &rest);
		bool handle_away(Client &c, std::istringstream &rest);
		bool handle_cnotice(Client &c, std::istringstream &rest);
		bool handle_cprivmsg(Client &c, std::istringstream &rest);
		bool handle_connect(Client &c, std::istringstream &rest);
		bool handle_die(Client &c, std::istringstream &rest);
		bool handle_error(Client &c, std::istringstream &rest);
		bool handle_help(Client &c, std::istringstream &rest);
		bool handle_info(Client &c, std::istringstream &rest);
		bool handle_invite(Client &c, std::istringstream &rest);
		bool handle_ison(Client &c, std::istringstream &rest);
		bool handle_join(Client &c, std::istringstream &rest);
		bool handle_kick(Client &c, std::istringstream &rest);
		bool handle_kill(Client &c, std::istringstream &rest);
		bool handle_knock(Client &c, std::istringstream &rest);
		bool handle_links(Client &c, std::istringstream &rest);
		bool handle_list(Client &c, std::istringstream &rest);
		bool handle_lusers(Client &c, std::istringstream &rest);
		bool handle_mode(Client &c, std::istringstream &rest);
		bool handle_motd(Client &c, std::istringstream &rest);
		bool handle_names(Client &c, std::istringstream &rest);
		bool handleNick(Client &c, std::istringstream &rest);
		bool handle_notice(Client &c, std::istringstream &rest);
		bool handle_oper(Client &c, std::istringstream &rest);
		bool handle_part(Client &c, std::istringstream &rest);
		bool handle_pass(Client &c, std::istringstream &rest);
		bool handle_ping(Client &c, std::istringstream &rest);
		bool handle_pong(Client &c, std::istringstream &rest);
		bool handlePrivMsg(Client &c, std::istringstream &rest);
		bool handleQuit(Client &c, std::istringstream &rest);
		bool handle_quote(Client &c, std::istringstream &rest);
		bool handle_rehash(Client &c, std::istringstream &rest);
		bool handle_rules(Client &c, std::istringstream &rest);
		bool handle_server(Client &c, std::istringstream &rest);
		bool handle_squery(Client &c, std::istringstream &rest);
		bool handle_squit(Client &c, std::istringstream &rest);
		bool handle_setname(Client &c, std::istringstream &rest);
		bool handle_silence(Client &c, std::istringstream &rest);
		bool handle_stats(Client &c, std::istringstream &rest);
		bool handle_summon(Client &c, std::istringstream &rest);
		bool handle_time(Client &c, std::istringstream &rest);
		bool handle_topic(Client &c, std::istringstream &rest);
		bool handle_trace(Client &c, std::istringstream &rest);
		bool handleUser(Client &c, std::istringstream &rest);
		bool handle_userhost(Client &c, std::istringstream &rest);
		bool handle_userip(Client &c, std::istringstream &rest);
		bool handle_users(Client &c, std::istringstream &rest);
		bool handle_version(Client &c, std::istringstream &rest);
		bool handle_wallops(Client &c, std::istringstream &rest);
		bool handle_watch(Client &c, std::istringstream &rest);
		bool handle_who(Client &c, std::istringstream &rest);
		bool handle_whois(Client &c, std::istringstream &rest);
		bool handle_whowas(Client &c, std::istringstream &rest);
		bool handleDcc(Client &c, std::istringstream &rest);
		bool handle_message(Client &c, std::istringstream &rest);
		bool handleRplWelcome(Client &c);
		bool handleRplYourhost(Client &c);
		bool handleRplCreated(Client &c);
		bool handleRplMyinfo(Client &c);
		bool handleRplBounce(Client &c);
		bool handleRplTracelink(Client &c);
		bool handleRplTraceconnecting(Client &c);
		bool handleRplTracehandshake(Client &c);
		bool handleRplTraceunknown(Client &c);
		bool handleRplTraceoperator(Client &c);
		bool handleRplTraceuser(Client &c);
		bool handleRplTraceserver(Client &c);
		bool handleRplTraceservice(Client &c);
		bool handleRplTracenewtype(Client &c);
		bool handleRplTraceclass(Client &c);
		bool handleRplTracereconnect(Client &c);
		bool handleRplStatslinkinfo(Client &c);
		bool handleRplStatscommands(Client &c);
		bool handleRplStatscline(Client &c);
		bool handleRplStatsnline(Client &c);
		bool handleRplStatsiline(Client &c);
		bool handleRplStatskline(Client &c);
		bool handleRplStatsqline(Client &c);
		bool handleRplStatsyline(Client &c);
		bool handleRplEndofstats(Client &c);
		bool handleRplUmodeis(Client &c);
		bool handleRplServiceinfo(Client &c);
		bool handleRplEndofservices(Client &c);
		bool handleRplService(Client &c);
		bool handleRplServlist(Client &c);
		bool handleRplServlistend(Client &c);
		bool handleRplStatsvline(Client &c);
		bool handleRplStatslline(Client &c);
		bool handleRplStatsuptime(Client &c);
		bool handleRplStatsoline(Client &c);
		bool handleRplStatshline(Client &c);
		bool handleRplStatsping(Client &c);
		bool handleRplStatsbline(Client &c);
		bool handleRplStatsdline(Client &c);
		bool handleRplLuserclient(Client &c);
		bool handleRplLuserop(Client &c);
		bool handleRplLuserunknown(Client &c);
		bool handleRplLuserchannels(Client &c);
		bool handleRplLuserme(Client &c);
		bool handleRplAdminme(Client &c);
		bool handleRplAdminloc1(Client &c);
		bool handleRplAdminloc2(Client &c);
		bool handleRplAdminemail(Client &c);
		bool handleRplTracelog(Client &c);
		bool handleRplTraceend(Client &c);
		bool handleRplTryagain(Client &c);
		bool handleRplNone(Client &c);
		bool handleRplAway(Client &c);
		bool handleRplUserhost(Client &c);
		bool handleRplIson(Client &c);
		bool handleRplUnaway(Client &c);
		bool handleRplNowaway(Client &c);
		bool handleRplWhoisuser(Client &c);
		bool handleRplWhoisserver(Client &c);
		bool handleRplWhoisoperator(Client &c);
		bool handleRplWhowasuser(Client &c);
		bool handleRplEndofwho(Client &c);
		bool handleRplWhoischanop(Client &c);
		bool handleRplWhoisidle(Client &c);
		bool handleRplEndofwhois(Client &c);
		bool handleRplWhoischannels(Client &c);
		bool handleRplListstart(Client &c);
		bool handleRplList(Client &c);
		bool handleRplListend(Client &c);
		bool handleRplChannelmodeis(Client &c);
		bool handleRplUniqopis(Client &c);
		bool handleRplNotopic(Client &c);
		bool handleRplTopic(Client &c);
		bool handleRplInviting(Client &c);
		bool handleRplSummoning(Client &c);
		bool handleRplInvitelist(Client &c);
		bool handleRplEndofinvitelist(Client &c);
		bool handleRplExceptlist(Client &c);
		bool handleRplEndofexceptlist(Client &c);
		bool handleRplVersion(Client &c);
		bool handleRplWhoreply(Client &c);
		bool handleRplNamreply(Client &c);
		bool handleRplKilldone(Client &c);
		bool handleRplClosing(Client &c);
		bool handleRplCloseend(Client &c);
		bool handleRplLinks(Client &c);
		bool handleRplEndoflinks(Client &c);
		bool handleRplEndofnames(Client &c);
		bool handleRplBanlist(Client &c);
		bool handleRplEndofbanlist(Client &c);
		bool handleRplEndofwhowas(Client &c);
		bool handleRplInfo(Client &c);
		bool handleRplMotd(Client &c);
		bool handleRplInfostart(Client &c);
		bool handleRplEndofinfo(Client &c);
		bool handleRplMotdstart(Client &c);
		bool handleRplEndofmotd(Client &c);
		bool handleRplYoureoper(Client &c);
		bool handleRplRehashing(Client &c);
		bool handleRplYoureservice(Client &c);
		bool handleRplMyportis(Client &c);
		bool handleRplTime(Client &c);
		bool handleRplUsersstart(Client &c);
		bool handleRplUsers(Client &c);
		bool handleRplEndofusers(Client &c);
		bool handleRplNousers(Client &c);
		bool handleErrNosuchnick(Client &c);
		bool handleErrNosuchserver(Client &c);
		bool handleErrNosuchchannel(Client &c);
		bool handleErrCannotsendtochan(Client &c);
		bool handleErrToomanychannels(Client &c);
		bool handleErrWasnosuchnick(Client &c);
		bool handleErrToomanytargets(Client &c);
		bool handleErrNosuchservice(Client &c);
		bool handleErrNoorigin(Client &c);
		bool handleErrNorecipient(Client &c);
		bool handleErrNotexttosend(Client &c);
		bool handleErrNotoplevel(Client &c);
		bool handleErrWildtoplevel(Client &c);
		bool handleErrBadmask(Client &c);
		bool handleErrUnknowncommand(Client &c);
		bool handleErrNomotd(Client &c);
		bool handleErrNoadmininfo(Client &c);
		bool handleErrFileerror(Client &c);
		bool handleErrNonicknamegiven(Client &c);
		bool handleErrErroneusnickname(Client &c);
		bool handleErrNicknameinuse(Client &c);
		bool handleErrNickcollision(Client &c);
		bool handleErrUnavailresource(Client &c);
		bool handleErrUsernotinchannel(Client &c);
		bool handleErrNotonchannel(Client &c);
		bool handleErrUseronchannel(Client &c);
		bool handleErrNologin(Client &c);
		bool handleErrSummondisabled(Client &c);
		bool handleErrUsersdisabled(Client &c);
		bool handleErrNotregistered(Client &c);
		bool handleErrNeedmoreparams(Client &c);
		bool handleErrAlreadyregistered(Client &c);
		bool handleErrNopermforhost(Client &c);
		bool handleErrPasswdmismatch(Client &c);
		bool handleErrYourebannedcreep(Client &c);
		bool handleErrYouwillbebanned(Client &c);
		bool handleErrKeyset(Client &c);
		bool handleErrChannelisfull(Client &c);
		bool handleErrUnknownmode(Client &c);
		bool handleErrInviteonlychan(Client &c);
		bool handleErrBannedfromchan(Client &c);
		bool handleErrBadchannelkey(Client &c);
		bool handleErrBadchanmask(Client &c);
		bool handleErrNochanmodes(Client &c);
		bool handleErrBanlistfull(Client &c);
		bool handleErrNoprivileges(Client &c);
		bool handleErrChanoprivsneeded(Client &c);
		bool handleErrCantkillserver(Client &c);
		bool handleErrRestricted(Client &c);
		bool handleErrUniqoprivsneeded(Client &c);
		bool handleErrNooperhost(Client &c);
		bool handleErrNoservicehost(Client &c);
		bool handleErrUmodeunknownflag(Client &c);
		bool handleErrUsersdontmatch(Client &c);

};

#endif
