#ifndef SERVER_HPP
# define SERVER_HPP

# include "main.hpp"
# include "Trie.hpp"
# include "Server.hpp"
# include "Client.hpp"
# include "Channel.hpp"
# include <iostream>
# include <sstream>
# include <queue>
# define SOCK_DOMAIN AF_LOCAL

# define  MAX_SOCKET_FD 2048U

class Server {
	typedef bool (Server::*cmdFn)(Client &c, std::istringstream &rest);
	typedef std::string (Server::*replyMsg)(Client &c);
	private:
		uint16_t				_port;
		int						_sockServerFD;
		std::string				_password;
		std::string				_ip;
		Trie<Server::cmdFn>		_commands;
		Trie<int>				_clientTrie;
		std::vector<Client *>	_clients;
		Trie<Channel *>			_channelTrie;
		std::list<Channel>		_channel;
		Trie<Server::replyMsg>	_replyMsg;
		// bool					_init();
		// bool					_clientAdd();

		bool					_validateAccess(Client *c, std::string &command);
		bool    				_validateCommand(cmdFn &func, std::string &command);
		const std::string		&_getPassword();
		Server() {};
		Server(const Server &src) {(void)src;};
	public:
		Server(uint16_t port, std::string password);
		~Server();
		// std::pair<size_t, std::string>	getVals();
		int 							newConnection();
		void							delClient(int fd);
		bool							run();
		bool							doCommand(size_t fd);
		Client							&getClient(size_t fd);
		// void							setClient(size_t fd);
		std::string						getIp(void) const;
		void							setIp(std::string ip);
		bool							sendToClient(Client &source, std::string message);
		bool							addRPLToClient(Client &source, uint32_t code);
		bool							sendRPLToClient(Client &source, uint32_t code);
		void							deconnectClient(int fd, std::string error, std::string message);
		std::queue<int>					poolOut;
		std::vector<int>				poolQuit;
		// std::vector<int>				poolInt;
		// c'est horrible
		bool handle_admin(Client &c, std::istringstream &rest);
		bool handle_away(Client &c, std::istringstream &rest);
		bool handle_cnotice(Client &c, std::istringstream &rest);
		bool handle_cprivmsg(Client &c, std::istringstream &rest);
		bool handle_connect(Client &c, std::istringstream &rest);
		bool handle_die(Client &c, std::istringstream &rest);
		bool handle_error(Client &c, std::istringstream &rest);
		bool handle_help(Client &c, std::istringstream &rest);
		bool handle_info(Client &c, std::istringstream &rest);
		bool handle_invite(Client &c, std::istringstream &rest);
		bool handle_ison(Client &c, std::istringstream &rest);
		bool handle_join(Client &c, std::istringstream &rest);
		bool handle_kick(Client &c, std::istringstream &rest);
		bool handle_kill(Client &c, std::istringstream &rest);
		bool handle_knock(Client &c, std::istringstream &rest);
		bool handle_links(Client &c, std::istringstream &rest);
		bool handle_list(Client &c, std::istringstream &rest);
		bool handle_lusers(Client &c, std::istringstream &rest);
		bool handle_mode(Client &c, std::istringstream &rest);
		bool handle_motd(Client &c, std::istringstream &rest);
		bool handle_names(Client &c, std::istringstream &rest);
		bool handleNick(Client &c, std::istringstream &rest);
		bool handle_notice(Client &c, std::istringstream &rest);
		bool handle_oper(Client &c, std::istringstream &rest);
		bool handle_part(Client &c, std::istringstream &rest);
		bool handle_pass(Client &c, std::istringstream &rest);
		bool handle_ping(Client &c, std::istringstream &rest);
		bool handle_pong(Client &c, std::istringstream &rest);
		bool handlePrivMsg(Client &c, std::istringstream &rest);
		bool handleQuit(Client &c, std::istringstream &rest);
		bool handle_quote(Client &c, std::istringstream &rest);
		bool handle_rehash(Client &c, std::istringstream &rest);
		bool handle_rules(Client &c, std::istringstream &rest);
		bool handle_server(Client &c, std::istringstream &rest);
		bool handle_squery(Client &c, std::istringstream &rest);
		bool handle_squit(Client &c, std::istringstream &rest);
		bool handle_setname(Client &c, std::istringstream &rest);
		bool handle_silence(Client &c, std::istringstream &rest);
		bool handle_stats(Client &c, std::istringstream &rest);
		bool handle_summon(Client &c, std::istringstream &rest);
		bool handle_time(Client &c, std::istringstream &rest);
		bool handle_topic(Client &c, std::istringstream &rest);
		bool handle_trace(Client &c, std::istringstream &rest);
		bool handleUser(Client &c, std::istringstream &rest);
		bool handle_userhost(Client &c, std::istringstream &rest);
		bool handle_userip(Client &c, std::istringstream &rest);
		bool handle_users(Client &c, std::istringstream &rest);
		bool handle_version(Client &c, std::istringstream &rest);
		bool handle_wallops(Client &c, std::istringstream &rest);
		bool handle_watch(Client &c, std::istringstream &rest);
		bool handle_who(Client &c, std::istringstream &rest);
		bool handle_whois(Client &c, std::istringstream &rest);
		bool handle_whowas(Client &c, std::istringstream &rest);
		bool handleDcc(Client &c, std::istringstream &rest);
		bool handle_message(Client &c, std::istringstream &rest);
		std::string handleRplWelcome(Client &c);
		std::string handleRplYourhost(Client &c);
		std::string handleRplCreated(Client &c);
		std::string handleRplMyinfo(Client &c);
		std::string handleRplBounce(Client &c);
		std::string handleRplTracelink(Client &c);
		std::string handleRplTraceconnecting(Client &c);
		std::string handleRplTracehandshake(Client &c);
		std::string handleRplTraceunknown(Client &c);
		std::string handleRplTraceoperator(Client &c);
		std::string handleRplTraceuser(Client &c);
		std::string handleRplTraceserver(Client &c);
		std::string handleRplTraceservice(Client &c);
		std::string handleRplTracenewtype(Client &c);
		std::string handleRplTraceclass(Client &c);
		std::string handleRplTracereconnect(Client &c);
		std::string handleRplStatslinkinfo(Client &c);
		std::string handleRplStatscommands(Client &c);
		std::string handleRplStatscline(Client &c);
		std::string handleRplStatsnline(Client &c);
		std::string handleRplStatsiline(Client &c);
		std::string handleRplStatskline(Client &c);
		std::string handleRplStatsqline(Client &c);
		std::string handleRplStatsyline(Client &c);
		std::string handleRplEndofstats(Client &c);
		std::string handleRplUmodeis(Client &c);
		std::string handleRplServiceinfo(Client &c);
		std::string handleRplEndofservices(Client &c);
		std::string handleRplService(Client &c);
		std::string handleRplServlist(Client &c);
		std::string handleRplServlistend(Client &c);
		std::string handleRplStatsvline(Client &c);
		std::string handleRplStatslline(Client &c);
		std::string handleRplStatsuptime(Client &c);
		std::string handleRplStatsoline(Client &c);
		std::string handleRplStatshline(Client &c);
		std::string handleRplStatsping(Client &c);
		std::string handleRplStatsbline(Client &c);
		std::string handleRplStatsdline(Client &c);
		std::string handleRplLuserclient(Client &c);
		std::string handleRplLuserop(Client &c);
		std::string handleRplLuserunknown(Client &c);
		std::string handleRplLuserchannels(Client &c);
		std::string handleRplLuserme(Client &c);
		std::string handleRplAdminme(Client &c);
		std::string handleRplAdminloc1(Client &c);
		std::string handleRplAdminloc2(Client &c);
		std::string handleRplAdminemail(Client &c);
		std::string handleRplTracelog(Client &c);
		std::string handleRplTraceend(Client &c);
		std::string handleRplTryagain(Client &c);
		std::string handleRplNone(Client &c);
		std::string handleRplAway(Client &c);
		std::string handleRplUserhost(Client &c);
		std::string handleRplIson(Client &c);
		std::string handleRplUnaway(Client &c);
		std::string handleRplNowaway(Client &c);
		std::string handleRplWhoisuser(Client &c);
		std::string handleRplWhoisserver(Client &c);
		std::string handleRplWhoisoperator(Client &c);
		std::string handleRplWhowasuser(Client &c);
		std::string handleRplEndofwho(Client &c);
		std::string handleRplWhoischanop(Client &c);
		std::string handleRplWhoisidle(Client &c);
		std::string handleRplEndofwhois(Client &c);
		std::string handleRplWhoischannels(Client &c);
		std::string handleRplListstart(Client &c);
		std::string handleRplList(Client &c);
		std::string handleRplListend(Client &c);
		std::string handleRplChannelmodeis(Client &c);
		std::string handleRplUniqopis(Client &c);
		std::string handleRplNotopic(Client &c);
		std::string handleRplTopic(Client &c);
		std::string handleRplInviting(Client &c);
		std::string handleRplSummoning(Client &c);
		std::string handleRplInvitelist(Client &c);
		std::string handleRplEndofinvitelist(Client &c);
		std::string handleRplExceptlist(Client &c);
		std::string handleRplEndofexceptlist(Client &c);
		std::string handleRplVersion(Client &c);
		std::string handleRplWhoreply(Client &c);
		std::string handleRplNamreply(Client &c);
		std::string handleRplKilldone(Client &c);
		std::string handleRplClosing(Client &c);
		std::string handleRplCloseend(Client &c);
		std::string handleRplLinks(Client &c);
		std::string handleRplEndoflinks(Client &c);
		std::string handleRplEndofnames(Client &c);
		std::string handleRplBanlist(Client &c);
		std::string handleRplEndofbanlist(Client &c);
		std::string handleRplEndofwhowas(Client &c);
		std::string handleRplInfo(Client &c);
		std::string handleRplMotd(Client &c);
		std::string handleRplInfostart(Client &c);
		std::string handleRplEndofinfo(Client &c);
		std::string handleRplMotdstart(Client &c);
		std::string handleRplEndofmotd(Client &c);
		std::string handleRplYoureoper(Client &c);
		std::string handleRplRehashing(Client &c);
		std::string handleRplYoureservice(Client &c);
		std::string handleRplMyportis(Client &c);
		std::string handleRplTime(Client &c);
		std::string handleRplUsersstart(Client &c);
		std::string handleRplUsers(Client &c);
		std::string handleRplEndofusers(Client &c);
		std::string handleRplNousers(Client &c);
		std::string handleErrNosuchnick(Client &c);
		std::string handleErrNosuchserver(Client &c);
		std::string handleErrNosuchchannel(Client &c);
		std::string handleErrCannotsendtochan(Client &c);
		std::string handleErrToomanychannels(Client &c);
		std::string handleErrWasnosuchnick(Client &c);
		std::string handleErrToomanytargets(Client &c);
		std::string handleErrNosuchservice(Client &c);
		std::string handleErrNoorigin(Client &c);
		std::string handleErrNorecipient(Client &c);
		std::string handleErrNotexttosend(Client &c);
		std::string handleErrNotoplevel(Client &c);
		std::string handleErrWildtoplevel(Client &c);
		std::string handleErrBadmask(Client &c);
		std::string handleErrUnknowncommand(Client &c);
		std::string handleErrNomotd(Client &c);
		std::string handleErrNoadmininfo(Client &c);
		std::string handleErrFileerror(Client &c);
		std::string handleErrNonicknamegiven(Client &c);
		std::string handleErrErroneusnickname(Client &c);
		std::string handleErrNicknameinuse(Client &c);
		std::string handleErrNickcollision(Client &c);
		std::string handleErrUnavailresource(Client &c);
		std::string handleErrUsernotinchannel(Client &c);
		std::string handleErrNotonchannel(Client &c);
		std::string handleErrUseronchannel(Client &c);
		std::string handleErrNologin(Client &c);
		std::string handleErrSummondisabled(Client &c);
		std::string handleErrUsersdisabled(Client &c);
		std::string handleErrNotregistered(Client &c);
		std::string handleErrNeedmoreparams(Client &c);
		std::string handleErrAlreadyregistered(Client &c);
		std::string handleErrNopermforhost(Client &c);
		std::string handleErrPasswdmismatch(Client &c);
		std::string handleErrYourebannedcreep(Client &c);
		std::string handleErrYouwillbebanned(Client &c);
		std::string handleErrKeyset(Client &c);
		std::string handleErrChannelisfull(Client &c);
		std::string handleErrUnknownmode(Client &c);
		std::string handleErrInviteonlychan(Client &c);
		std::string handleErrBannedfromchan(Client &c);
		std::string handleErrBadchannelkey(Client &c);
		std::string handleErrBadchanmask(Client &c);
		std::string handleErrNochanmodes(Client &c);
		std::string handleErrBanlistfull(Client &c);
		std::string handleErrNoprivileges(Client &c);
		std::string handleErrChanoprivsneeded(Client &c);
		std::string handleErrCantkillserver(Client &c);
		std::string handleErrRestricted(Client &c);
		std::string handleErrUniqoprivsneeded(Client &c);
		std::string handleErrNooperhost(Client &c);
		std::string handleErrNoservicehost(Client &c);
		std::string handleErrUmodeunknownflag(Client &c);
		std::string handleErrUsersdontmatch(Client &c);

};

#endif
